### ISSUE TITLE
Cannot reproduce the results of ResNet-56 on CIFAR-10

### ISSUE THREAD

**Issue by kyuusaku** [ltrottier/pelu.resnet.torch#3]
Hi, 

I tried to reproduce the results of ResNet-56 on CIFAR-10, which is reported as 5.65 error rate in the paper.

I ran the following scripts for reproduction. But cannot achieve the same result. My results are higher. I ran five times and got 5.93, 5.93, 5.79, 6.03, 5.97 respectively. The average is 5.93. 

`th main.lua -dataset cifar10 -nGPU 4 -batchSize 128 -nEpochs 200 -depth 56 -shortcutType A -weightDecay 0.001 -nThreads 8`

Did I miss any thing? Thank you for any help.

**Comment by kyuusaku** [comment]
@ltrottier

**Comment by ltrottier** [comment]
I made an error in the paper. I was using a batch size of 256 instead of 128, and reporting the minimum value. I recently re-ran my experiments, and I uploaded the results. Using this:
```
th main.lua -netType resnet-pelu -dataset cifar10 -batchSize 256 -nEpochs 200 -depth 56 -shortcutType A -weightDecay 0.001
```
I got 5.91% mean and 5.68% min over 5 tries. In the current version of the paper, I don't use these results though. I only use the 110 layers.
